### ISSUE TITLE
Campsite Facility Reserveration Information, Historical, Current and Future

### ISSUE THREAD

**Issue by thecaddy** [USDA/RIDB#30]
As someone looking to plan a trip, the reservation levels historically and currently would be invaluable to plan the time of year to travel.

**Comment by danparker-nsite** [comment]
Joel,

I have good news! Ten years of historical reservation data is now available in the RIDB. There are [API endpoints](http://usda.github.io/RIDB/#Historical%20Reservations) to get historical data collections and resources. If you'd rather just download the data in yearly CSV files, [we have those](https://ridb.recreation.gov/?action=datadownload) too. The [data dictionary](http://usda.github.io/RIDB/#Historical%20Reservation) explains what's contained in the data sets. 

Current reservation data is not available in the RIDB, but we're looking to add this data in the future. Thanks for your patience as we worked to add this data!

**Comment by gizm00** [comment]
This is fantastic !!!! Thank you so much for your efforts!

**Comment by gizm00** [comment]
Dan - also, any news on a recreation.gov API for reservations? I understand
a vendor is being chosen this summer and I was hoping to hear some news
about an API for third party bookings.

Thanks for all your efforts!

Sev



On Jul 20, 2016, at 1:02 PM, Dan Parker <notifications@github.com> wrote:

Joel,

I have good news! Ten years of historical reservation data is now available
in the RIDB. There are API endpoints
<http://usda.github.io/RIDB/#Historical%20Reservations> to get historical
data collections and resources. If you'd rather just download the data in
yearly CSV files, we have those
<https://ridb.recreation.gov/?action=datadownload> too. The data dictionary
<http://usda.github.io/RIDB/#Historical%20Reservation> explains what's
contained in the data sets.

Current reservation data is not available in the RIDB, but we're looking to
add this data in the future. Thanks for your patience as we worked to add
this data!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/USDA/RIDB/issues/30#issuecomment-234064624>, or mute
the thread

**Comment by thecaddy** [comment]
This is great to hear!  Thanks for the hard work.

**Comment by danparker-nsite** [comment]
Sev,

Sorry, I don't have any news about an API for third party bookings at this time.

**Comment by GitStu** [comment]
Sev,
I'm on the Rec.gov team and I work with Dan in managing the RIDB.  In the new contract expected to begin this fall we will be looking into building an API for 3rd party bookings.  We cannot yet forecast a delivery date yet since we haven't begun the new contract.

**Comment by gizm00** [comment]
Thanks Stu! Really excited about the work you all are doing.

**Comment by geppy** [comment]
I'm also interested in accessing the availability and registration system.  @danparker-sts I see you closed the issue now that the first part of the request has been resolved, should I make a new issue to track the upcoming booking system?

**Comment by GitStu** [comment]
Hello,
The reservation/availability API has been identified for (at least) investigation into implementation under the new contract we expect to begin this spring.  No need to create an issue here on GitHub, but thank you for offering.

Stu

**Comment by geppy** [comment]
Okay.  Thanks!
