### ISSUE TITLE
Why does the USDA manage this?

### ISSUE THREAD

**Issue by CrazyPython** [USDA/RIDB#42]
What does recreation have to do with agriculture?

**Comment by GitStu** [comment]
Good question.  The Forest Service is the managing/administrative agency that helps operate the Recreation One Stop/Recreation.gov program (which includes the RIDB database), and the Forest Service is one of 12 participating agencies that contribute recreation inventory data to RIDB/Rec.gov.  Since the FS is a USDA agency we are using USDA GitHub space.
