### ISSUE TITLE
Okanogan-Wenatchee National Forest deletion?

### ISSUE THREAD

**Issue by reidab** [USDA/RIDB#53]
It looks like all the data for the [Okanogan-Wenatchee National Forest](https://www.fs.usda.gov/okawen/) and its facilities disappeared from the RIDB in the last couple of days. Was this an intentional change?

**Comment by GitStu** [comment]
Reid - That is odd.  I can’t find it either.  Send me some of the facilities if you know them so I can look for those too.  Don’t know if intentional – this would probably originate from the Forest Service who feeds the data into our Rec.gov system.

Sue/Justin – Are either of you aware that Okanogan-Wenatchee data is not coming to RIDB as of recently?  Don’t yet know if this pertains to just the Forest or all/many of its child facilities.  Any ideas?

[Forest Service Shield]

Stu Gregory
RIDB Data Manager

Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 801-602-2435
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[USDA Logo]<http://usda.gov/>[Forest Service Twitter]<https://twitter.com/forestservice>[USDA Facebook]<https://www.facebook.com/pages/US-Forest-Service/1431984283714112>

Caring for the land and serving people

**Comment by GitStu** [comment]
Thank you.

[Forest Service Shield]

Stu Gregory
RIDB Data Manager

Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 801-602-2435
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[USDA Logo]<http://usda.gov/>[Forest Service Twitter]<https://twitter.com/forestservice>[USDA Facebook]<https://www.facebook.com/pages/US-Forest-Service/1431984283714112>

Caring for the land and serving people

**Comment by GitStu** [comment]
Reid – I have emailed this forest asking what the problem may be and if the data can be restored for our API.  We are not sure where the root of this problem lies.  There has been a recent funding reduction for USFS web services that might be causing this, but that is only a guess.  Waiting to hear back from the forest.

[Forest Service Shield]

Stu Gregory
RIDB Data Manager

Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 801-602-2435
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[USDA Logo]<http://usda.gov/>[Forest Service Twitter]<https://twitter.com/forestservice>[USDA Facebook]<https://www.facebook.com/pages/US-Forest-Service/1431984283714112>

Caring for the land and serving people

**Comment by GitStu** [comment]
Reid – the Okanogan-Wenatchee NF and its children records are back and available again.  A setting in the Forest Service web system that feeds us the records needed to be re-set.

[Forest Service Shield]

Stu Gregory
RIDB Data Manager

Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 801-602-2435
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[USDA Logo]<http://usda.gov/>[Forest Service Twitter]<https://twitter.com/forestservice>[USDA Facebook]<https://www.facebook.com/pages/US-Forest-Service/1431984283714112>

Caring for the land and serving people

**Comment by GitStu** [comment]
I have some part-time funding from Rec for the month of April, so I will go ahead and investigate this as soon as I have a chance.

From: Gregory, Stuart -FS
Sent: Monday, March 26, 2018 7:06 AM
To: USDA/RIDB <reply@reply.github.com>; USDA/RIDB <RIDB@noreply.github.com>; Valente, Susan - FS <svalente@fs.fed.us>; Thornton, Justin -FS <jthornton02@fs.fed.us>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: RE: [USDA/RIDB] Okanogan-Wenatchee National Forest deletion? (#53)

Reid - That is odd.  I can’t find it either.  Send me some of the facilities if you know them so I can look for those too.  Don’t know if intentional – this would probably originate from the Forest Service who feeds the data into our Rec.gov system.

Sue/Justin – Are either of you aware that Okanogan-Wenatchee data is not coming to RIDB as of recently?  Don’t yet know if this pertains to just the Forest or all/many of its child facilities.  Any ideas?

[Forest Service Shield]

Stu Gregory
RIDB Data Manager

Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 801-602-2435
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[USDA Logo]<http://usda.gov/>[Forest Service Twitter]<https://twitter.com/forestservice>[USDA Facebook]<https://www.facebook.com/pages/US-Forest-Service/1431984283714112>

Caring for the land and serving people

**Comment by reidab** [comment]
Thanks so much for looking into this and figuring it out! 🌲🎉
