### ISSUE TITLE
Real Time Availability Endpoint?

### ISSUE THREAD

**Issue by mceoin** [USDA/RIDB#9]
Hi there USDA/RIDB!

Is there a way for me to query if a website is available in real-time or close-to real-time? I'm kicking around ideas before the RIDB hackathon. http://openglobe.github.io/myamerica-devsummit/

Fantastic to see this come out. Excellent work!

**Comment by GitStu** [comment]
Hi Eoin,
Real time availability of Recreation.gov inventory is not yet possible through the new RIDB API.  This is due to the reservable data being housed in a separate database than RIDB, and it gets sent to the RIDB nightly.  So the RIDB does reflect availability, but it is not real time due to the data updates needed between the 2 databases nightly.  In the new contract we intend to consolidate both sets so real time availability can be accessed.

Thanks for your interest in the hackathon.  We look forward to seeing you there in a few weeks!

Stu

[Forest Service Shield]

Stu Gregory
RIDB Program Manager, PMP

Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 385-235-2971
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[http://wwwstatic.fs.usda.gov/images/email/usda-logo.png]<http://usda.gov/>[Twitter Logo]<https://twitter.com/forestservice>[Facebook Logo]<http://facebook.com/USDA>

Caring for the land and serving people

**Comment by GitStu** [comment]
My mistake on this issue.  The reservable/availability data is populated to the RIDB from a separate database weekly as opposed to nightly.
